### ISSUE TITLE
how to generate data?

### ISSUE THREAD

**Issue by hate-deadline** [pbcquoc/crnn#4]
Could you please show me the way you used to generate this data?

**Comment by pbcquoc** [comment]
Bạn có thể sài source code này https://github.com/Belval/TextRecognitionDataGenerator, cái này thì chưa support tiếng việt.
Nhưng mà bạn có thể customer lại code được. bổ sung thêm font tiếng việt vào. và dùng Viet74k làm text để generate.

Hoặc cũng có thể sài source này https://github.com/tmbarchive/ocropy/blob/master/ocropus-linegen

Còn phương pháp cụ thể thì mình nghĩ bạn chỉ cần biết tí về xử lý ảnh và đọc tí code người ta làm thì hiểu ngay thôi ak.
